name: b24
profile: b24
version: '0.1.0'
require-dbt-version: ['>=0.1.0', '<1.1.0']
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
seed-paths:
  - data
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target
clean-targets:
    - "target"
    
vars:
  load_date: 'today()'
  #'current_timestamp'
  beg_id: 0
#  DBT_SOURCE_DATABASE: 'default'
#  DBT_SOURCE_SHEMA: 'default'

models:
  +on_schema_change: "sync_all_columns"
#  +bind: false
#  +pre-hook: "{{ logging.log_model.start_event() }}"
#  +post-hook: "{{ logging.log_model.end_event() }}"
  b24:
    stage:
      tags:
        - 'stage'
      materialized: view
    bi:
      tags:
        - 'bi'
      materialized: incremental