config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True

b24:
  outputs:

    dev:
      type: clickhouse
      schema: default
      host: "{{ env_var('DBT_HOST') }}"
      port: 9440
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      secure: True

  target: dev
