version: 2

sources:
  - name: src
    #database: clickhouse
    schema: default
    tables:
      - name: b24
      - name: b24users
      - name: b24departments
      - name: regions
     
models:
  - name: v_stg_b24
    description: b24
    columns:
      - name: id
        tests:
          - not_null
          - unique
